### ISSUE TITLE
Unable to delete bucket in cloudian hyperstore

### ISSUE THREAD

**Issue by yadu-boss** [EMCECS/bucket-wipe#3]
HI Team,

I tried to deleted bucket from clodian hyperstore (100% s3 compatible from windows server2012 r2)  am getting below error. 
Please find below error.
I posted two error with error log, one after the other please find both.

 
C:\bucketwipe\bucket-wipe-master\bucket-wipe-master\build\libs>"C:\Program Files\Java\jre1.8.0_121\bin\java" -jar bucket-wipe-1.10.jar -a xxxxxxxxxxxxxxxxx -e https://xxxxxxxxxxxxxxxxxxxxxxxx:8443 -s xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  dell
0          WARN  [Thread-2       ] EcsHostListProvider: unable to retrieve node list from xxxxxxxxxxxxxxxxxxxxxx.net
com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
        at com.emc.rest.smart.ecs.EcsHostListProvider.getDataNodes(EcsHostListProvider.java:150)
        at com.emc.rest.smart.ecs.EcsHostListProvider.getHostList(EcsHostListProvider.java:85)
        at com.emc.rest.smart.PollingDaemon.run(PollingDaemon.java:63)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:827)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
        ... 7 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 29 more
74         WARN  [Thread-2       ] EcsHostListProvider: could not retrieve node list for VDC xxxxxxxxxxxxxxxxxx.net
100        WARN  [Thread-2       ] PollingDaemon: health check failed for xxxxxxxxxxxxxxxxxxxxxxx.net; host is marked unhealthy
com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
        at com.emc.rest.smart.ecs.EcsHostListProvider.runHealthCheck(EcsHostListProvider.java:104)
        at com.emc.rest.smart.PollingDaemon.run(PollingDaemon.java:76)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:827)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
        ... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 22 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 28 more
Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Last key before error: null
usage: java -jar bucket-wipe.jar [options] <bucket-name>
 -a,--access-key <access-key>   the S3 access key
 -e,--endpoint <URI>            the endpoint to connect to, including
                                protocol, host, and port
 -h,--help                      displays this help text
 -hier,--hierarchical           Enumerate the bucket hierarchically.  This
                                is recommended for ECS's
                                filesystem-enabled buckets.
    --keep-bucket               do not delete the bucket when done
 -l,--key-list <file>           instead of listing bucket, delete objects
                                matched in source file key list
    --no-smart-client           disables the ECS smart-client. use this
                                option with an external load balancer
 -p,--prefix <prefix>           deletes only objects under the specified
                                prefix
 -s,--secret-key <secret-key>   the secret key
    --stacktrace                displays full stack trace of errors
 -t,--threads <threads>         number of threads to use
    --vhost                     enables DNS buckets and turns off load
                                balancer

**Error log2**  with atmos

                                balancer

C:\bucketwipe\bucket-wipe-master\bucket-wipe-master\build\libs>"C:\Program Files\Java\jre1.8.0_121\bin\java" -jar bucket-wipe-1.10.jar --atmos -e https://xxxxxxxxxxxxxxxxxxxxx:8443 -a xxxxxxxxxxxxxxxxx -s xxxxxxxxxxxxxxxxxxxxxxxxx --no-smart-client -p dell
Error: Missing required options: e, a, s
usage: java -jar bucket-wipe.jar [options] <bucket-name>
 -a,--access-key <access-key>   the S3 access key
 -e,--endpoint <URI>            the endpoint to connect to, including
                                protocol, host, and port
 -h,--help                      displays this help text
 -hier,--hierarchical           Enumerate the bucket hierarchically.  This
                                is recommended for ECS's
                                filesystem-enabled buckets.
    --keep-bucket               do not delete the bucket when done
 -l,--key-list <file>           instead of listing bucket, delete objects
                                matched in source file key list
    --no-smart-client           disables the ECS smart-client. use this
                                option with an external load balancer
 -p,--prefix <prefix>           deletes only objects under the specified
                                prefix
 -s,--secret-key <secret-key>   the secret key
    --stacktrace                displays full stack trace of errors
 -t,--threads <threads>         number of threads to use
    --vhost                     enables DNS buckets and turns off load
                                balancer

**Comment by twincitiesguy** [comment]
Cleaning up old issues...

In case anyone else lands here from searching:
* The first error above is because you are using an untrusted SSL certificate - you need to add the S3 SSL certificate to the java trust store before you can connect to it from any java application.
* The second error above is because there is no `--atmos` option in the version of bucket-wipe you were using (it is not present in the help text that is printed), so any options after that are ignored
